### ISSUE TITLE
Missing LaTex dependencies

### ISSUE THREAD

**Issue by OpenJohnMacGregor** [elisa-tech/ELISA-White-Papers#3]
I installed the TexStudio package on a manilla OpenSuse (Leap 15.2) system.

Upon opening the White Paper document in TexStudio, I encountered the following "unknown commands".  After installing the listed packages I had the documented results. (Format: unreognised command - packages installed - end result)

A list of additional packages to be installed should be included in the Readme

newcommandx - newcommand - command recognised
todo - todo, todonotes - command unknown

Addendum:  todo works but the commentJK doesn't

**Comment by Jochen-Kall** [comment]
Hi John,

Normally tex should ask you whenever there is a package not yet installed on your machine whether you want it downloaded and installed. 
Listing the packages sure is possible, but kind of redundant, since all packages are in one list in the classfile anyways.

\commentJK is a wrapper macro I defined in line 6 around the \todo command to differentiate my comments from others, Idea was for other commenters to define an anlogous macro with different colors for their comments to tell them apart in the compiled pdf.

Just so we are on the same page, texstudio tells you unknown command, but the document compiles just fine right? 
In that case it's the help system of texstudio not recognizing the todo package macros, that can be easily remedied though, open your texstudio in the main menu:
options ->configure texstudio->autocompletion and check the box of the "todonotes.cwl" package, that tells texstudio to recognize the macros defined in the todonotes package, for some reason it does not detect that the package is used in the document.

As for the \commentJK macro, to teach the editor to recognize it, I'd have to create a custom .cwl file for it, and you would have to put it in your texstudio install folder if I recall correctly, which is why I didn't bother. Actually, that is 6 year old knowledge, maybe something easier can be done nowadays, I'll have a look.

**Comment by Jochen-Kall** [comment]
On further investigation, Texstudio does recognize macros defined by \newcommand afterwards, so I just defined the commmentJK macro using \newcommand instead of \newcommandx which was not needed anyways, now the macro is properly recongnized.

For some reason the \toprule \midrule etc macros are not recognized on my machine, if you have the same issue just checkmark "booktabs.cwl" autocomplete, at least on my machine, I don't have a single unrecognized macro left after doing that :)

**Comment by OpenJohnMacGregor** [comment]
Thanks for the TexStudio advice Jochen.

Neither newcommand nor todo were installed on my machine and TexStudio didn't suggest installing it (actually, I expected it to) so I used the operating system installer to install them instead.  I saw some documentation about CTAN, but didn't look further.

The \toprule. \midrule etc. worked for me out of the box.

Perhaps the "getting started" part of the wiki should say that one should check that all the packages referenced in the .cls file have been installed (probably a no-brainer for experienced LaTex users)

**Comment by Jochen-Kall** [comment]
Well I must admit, for windows at least, I always urge people to install a full Miktex, meaning all packages will be installed, that uses 4 GB of your disc space give or take, but you never have to worry about that stuff again, since the on the fly installation has been very unreliable in my experience at least.
There also is the possiblity it is switched off on your machine, not sure what the default setting is. Experience Latex users will directly know what to do based on the error message the compiler prints, but yeah I'll add it to the wiki.

**Comment by mikulcakCQ** [comment]
MikTex has only (fairly) recently added support for Linux. @OpenJohnMacGregor, you probably installed LaTeX via your package manager, so you probably only have a small subset of all LaTeX packages. On OpenSuse, the group of all packages should be  `texlive-scheme-full` and `texlive-collection-latex`, so I guess it's `zypper install  texlive-scheme-full texlive-collection-latex`

As Jochen said, it requires a lot of space, however.

**Comment by pahmann** [comment]
Closed as resolved by comment from @mikulcakCQ
